package com.loro;


import com.sun.jna.Library;
import com.sun.jna.Pointer;

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
interface UniffiLib extends Library {
    UniffiLib INSTANCE = UniffiLibInitializer.load();

    
    // The Cleaner for the whole library
    static UniffiCleaner CLEANER = UniffiCleaner.create();
    
    Pointer uniffi_loro_fn_clone_awareness(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_awareness(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_awareness_new(Long peer, Long timeout, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_awareness_apply(Pointer ptr, RustBuffer.ByValue encodedPeersInfo, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_awareness_encode(Pointer ptr, RustBuffer.ByValue peers, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_awareness_encode_all(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_awareness_get_all_states(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_awareness_get_local_state(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Long uniffi_loro_fn_method_awareness_peer(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_awareness_remove_outdated(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_awareness_set_local_state(Pointer ptr, Pointer value, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_changeancestorstraveler(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_changeancestorstraveler(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_changeancestorstraveler(UniffiVTableCallbackInterfaceChangeAncestorsTraveler vtable);
    Byte uniffi_loro_fn_method_changeancestorstraveler_travel(Pointer ptr, RustBuffer.ByValue change, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_configure(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_configure(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_configure_fork(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Long uniffi_loro_fn_method_configure_merge_interval(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_configure_record_timestamp(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_configure_set_merge_interval(Pointer ptr, Long interval, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_configure_set_record_timestamp(Pointer ptr, Byte record, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_configure_text_style_config(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_containeridlike(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_containeridlike(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_containeridlike(UniffiVTableCallbackInterfaceContainerIdLike vtable);
    RustBuffer.ByValue uniffi_loro_fn_method_containeridlike_as_container_id(Pointer ptr, RustBuffer.ByValue ty, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_cursor(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_cursor(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_cursor_new(RustBuffer.ByValue id, RustBuffer.ByValue container, RustBuffer.ByValue side, Integer originPos, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_diffbatch(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_diffbatch(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_diffbatch_new(UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_diffbatch_get_diff(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_diffbatch_push(Pointer ptr, RustBuffer.ByValue cid, RustBuffer.ByValue diff, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_fractionalindex(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_fractionalindex(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_fractionalindex_from_bytes(RustBuffer.ByValue bytes, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_fractionalindex_from_hex_string(RustBuffer.ByValue str, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_fractionalindex_to_string(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_frontiers(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_frontiers(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_frontiers_decode(RustBuffer.ByValue bytes, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_frontiers_from_id(RustBuffer.ByValue id, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_frontiers_from_ids(RustBuffer.ByValue ids, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_frontiers_new(UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_frontiers_encode(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_frontiers_eq(Pointer ptr, Pointer other, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_localupdatecallback(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_localupdatecallback(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_localupdatecallback(UniffiVTableCallbackInterfaceLocalUpdateCallback vtable);
    void uniffi_loro_fn_method_localupdatecallback_on_local_update(Pointer ptr, RustBuffer.ByValue update, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_lorocounter(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_lorocounter(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_lorocounter_new(UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorocounter_decrement(Pointer ptr, Double value, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorocounter_doc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorocounter_get_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Double uniffi_loro_fn_method_lorocounter_get_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorocounter_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorocounter_increment(Pointer ptr, Double value, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorocounter_is_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorocounter_is_deleted(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_lorodoc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_lorodoc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_lorodoc_new(UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_apply_diff(Pointer ptr, Pointer diff, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_attach(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_check_state_correctness_slow(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_checkout(Pointer ptr, Pointer frontiers, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_checkout_to_latest(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_clear_next_commit_options(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_cmp_with_frontiers(Pointer ptr, Pointer other, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_commit(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_commit_with(Pointer ptr, RustBuffer.ByValue options, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_compact_change_store(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_config(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_config_default_text_style(Pointer ptr, RustBuffer.ByValue textStyle, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_config_text_style(Pointer ptr, Pointer textStyle, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_detach(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_diff(Pointer ptr, Pointer a, Pointer b, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_json_in_id_span(Pointer ptr, RustBuffer.ByValue idSpan, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_json_updates(Pointer ptr, Pointer startVv, Pointer endVv, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_json_updates_without_peer_compression(Pointer ptr, Pointer startVv, Pointer endVv, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_shallow_snapshot(Pointer ptr, Pointer frontiers, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_snapshot(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_snapshot_at(Pointer ptr, Pointer frontiers, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_state_only(Pointer ptr, RustBuffer.ByValue frontiers, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_updates(Pointer ptr, Pointer vv, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_export_updates_in_range(Pointer ptr, RustBuffer.ByValue spans, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_find_id_spans_between(Pointer ptr, Pointer from, Pointer to, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_fork(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_fork_at(Pointer ptr, Pointer frontiers, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_free_diff_calculator(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_free_history_cache(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_frontiers_to_vv(Pointer ptr, Pointer frontiers, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_by_path(Pointer ptr, RustBuffer.ByValue path, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_by_str_path(Pointer ptr, RustBuffer.ByValue path, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_change(Pointer ptr, RustBuffer.ByValue id, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_changed_containers_in(Pointer ptr, RustBuffer.ByValue id, Integer len, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_get_counter(Pointer ptr, Pointer id, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_cursor_pos(Pointer ptr, Pointer cursor, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_deep_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_deep_value_with_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_get_list(Pointer ptr, Pointer id, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_get_map(Pointer ptr, Pointer id, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_get_movable_list(Pointer ptr, Pointer id, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_path_to_container(Pointer ptr, RustBuffer.ByValue id, UniffiRustCallStatus uniffi_out_errmk);
    Integer uniffi_loro_fn_method_lorodoc_get_pending_txn_len(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_get_text(Pointer ptr, Pointer id, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_get_tree(Pointer ptr, Pointer id, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_get_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorodoc_has_container(Pointer ptr, RustBuffer.ByValue id, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorodoc_has_history_cache(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_import(Pointer ptr, RustBuffer.ByValue bytes, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_import_batch(Pointer ptr, RustBuffer.ByValue bytes, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_import_json_updates(Pointer ptr, RustBuffer.ByValue json, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_import_with(Pointer ptr, RustBuffer.ByValue bytes, RustBuffer.ByValue origin, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorodoc_is_detached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorodoc_is_shallow(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_jsonpath(Pointer ptr, RustBuffer.ByValue path, UniffiRustCallStatus uniffi_out_errmk);
    Long uniffi_loro_fn_method_lorodoc_len_changes(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Long uniffi_loro_fn_method_lorodoc_len_ops(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_log_estimate_size(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorodoc_minimize_frontiers(Pointer ptr, Pointer frontiers, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_oplog_frontiers(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_oplog_vv(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Long uniffi_loro_fn_method_lorodoc_peer_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_revert_to(Pointer ptr, Pointer version, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_set_change_merge_interval(Pointer ptr, Long interval, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_set_next_commit_message(Pointer ptr, RustBuffer.ByValue msg, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_set_next_commit_options(Pointer ptr, RustBuffer.ByValue options, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_set_next_commit_origin(Pointer ptr, RustBuffer.ByValue origin, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_set_next_commit_timestamp(Pointer ptr, Long timestamp, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_set_peer_id(Pointer ptr, Long peer, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_set_record_timestamp(Pointer ptr, Byte record, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_shallow_since_vv(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_state_frontiers(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_state_vv(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_subscribe(Pointer ptr, RustBuffer.ByValue containerId, Pointer subscriber, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_subscribe_local_update(Pointer ptr, Pointer callback, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_subscribe_root(Pointer ptr, Pointer subscriber, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorodoc_travel_change_ancestors(Pointer ptr, RustBuffer.ByValue ids, Pointer f, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorodoc_vv_to_frontiers(Pointer ptr, Pointer vv, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_lorolist(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_lorolist(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_lorolist_new(UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorolist_clear(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorolist_delete(Pointer ptr, Integer pos, Integer len, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_doc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_get(Pointer ptr, Integer index, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_get_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_get_cursor(Pointer ptr, Integer pos, RustBuffer.ByValue side, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_get_deep_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_get_id_at(Pointer ptr, Integer pos, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_get_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorolist_insert(Pointer ptr, Integer pos, Pointer v, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorolist_insert_counter_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorolist_insert_list_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorolist_insert_map_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorolist_insert_movable_list_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorolist_insert_text_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorolist_insert_tree_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorolist_is_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorolist_is_deleted(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorolist_is_empty(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Integer uniffi_loro_fn_method_lorolist_len(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_pop(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorolist_push(Pointer ptr, Pointer v, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorolist_to_vec(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_loromap(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_loromap(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_loromap_new(UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromap_clear(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromap_delete(Pointer ptr, RustBuffer.ByValue key, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_doc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_get(Pointer ptr, RustBuffer.ByValue key, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_get_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_get_deep_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_get_last_editor(Pointer ptr, RustBuffer.ByValue key, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_get_or_create_counter_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_get_or_create_list_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_get_or_create_map_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_get_or_create_movable_list_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_get_or_create_text_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_get_or_create_tree_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_get_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromap_insert(Pointer ptr, RustBuffer.ByValue key, Pointer v, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_insert_counter_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_insert_list_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_insert_map_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_insert_movable_list_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_insert_text_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromap_insert_tree_container(Pointer ptr, RustBuffer.ByValue key, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_loromap_is_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_loromap_is_deleted(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_loromap_is_empty(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_keys(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Integer uniffi_loro_fn_method_loromap_len(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromap_values(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_loromovablelist(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_loromovablelist(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_loromovablelist_new(UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromovablelist_clear(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromovablelist_delete(Pointer ptr, Integer pos, Integer len, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_doc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get(Pointer ptr, Integer index, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get_creator_at(Pointer ptr, Integer pos, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get_cursor(Pointer ptr, Integer pos, RustBuffer.ByValue side, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get_deep_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get_last_editor_at(Pointer ptr, Integer pos, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get_last_mover_at(Pointer ptr, Integer pos, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_get_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromovablelist_insert(Pointer ptr, Integer pos, Pointer v, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_insert_counter_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_insert_list_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_insert_map_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_insert_movable_list_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_insert_text_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_insert_tree_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_loromovablelist_is_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_loromovablelist_is_deleted(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_loromovablelist_is_empty(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Integer uniffi_loro_fn_method_loromovablelist_len(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromovablelist_mov(Pointer ptr, Integer from, Integer to, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_pop(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromovablelist_push(Pointer ptr, Pointer v, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_loromovablelist_set(Pointer ptr, Integer pos, Pointer value, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_set_counter_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_set_list_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_set_map_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_set_movable_list_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_set_text_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_loromovablelist_set_tree_container(Pointer ptr, Integer pos, Pointer child, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_loromovablelist_to_vec(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_lorotext(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_lorotext(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_lorotext_new(UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_apply_delta(Pointer ptr, RustBuffer.ByValue delta, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_delete(Pointer ptr, Integer pos, Integer len, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_delete_utf8(Pointer ptr, Integer pos, Integer len, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_doc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_get_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_get_cursor(Pointer ptr, Integer pos, RustBuffer.ByValue side, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_get_editor_at_unicode_pos(Pointer ptr, Integer pos, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_get_richtext_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_insert(Pointer ptr, Integer pos, RustBuffer.ByValue s, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_insert_utf8(Pointer ptr, Integer pos, RustBuffer.ByValue s, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotext_is_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotext_is_deleted(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotext_is_empty(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Integer uniffi_loro_fn_method_lorotext_len_unicode(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Integer uniffi_loro_fn_method_lorotext_len_utf16(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Integer uniffi_loro_fn_method_lorotext_len_utf8(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_mark(Pointer ptr, Integer from, Integer to, RustBuffer.ByValue key, Pointer value, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_push_str(Pointer ptr, RustBuffer.ByValue s, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_slice(Pointer ptr, Integer startIndex, Integer endIndex, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_splice(Pointer ptr, Integer pos, Integer len, RustBuffer.ByValue s, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_to_delta(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotext_to_string(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_unmark(Pointer ptr, Integer from, Integer to, RustBuffer.ByValue key, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_update(Pointer ptr, RustBuffer.ByValue s, RustBuffer.ByValue options, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotext_update_by_line(Pointer ptr, RustBuffer.ByValue s, RustBuffer.ByValue options, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_lorotree(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_lorotree(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_lorotree_new(UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_children(Pointer ptr, RustBuffer.ByValue parent, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_children_num(Pointer ptr, RustBuffer.ByValue parent, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotree_contains(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_create(Pointer ptr, RustBuffer.ByValue parent, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_create_at(Pointer ptr, RustBuffer.ByValue parent, Integer index, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotree_delete(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotree_disable_fractional_index(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_doc(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotree_enable_fractional_index(Pointer ptr, Byte jitter, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_fractional_index(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_get_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_get_last_move_id(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_method_lorotree_get_meta(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_get_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_get_value_with_meta(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotree_is_attached(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotree_is_deleted(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotree_is_fractional_index_enabled(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_lorotree_is_node_deleted(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotree_mov(Pointer ptr, RustBuffer.ByValue target, RustBuffer.ByValue parent, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotree_mov_after(Pointer ptr, RustBuffer.ByValue target, RustBuffer.ByValue after, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotree_mov_before(Pointer ptr, RustBuffer.ByValue target, RustBuffer.ByValue before, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_lorotree_mov_to(Pointer ptr, RustBuffer.ByValue target, RustBuffer.ByValue parent, Integer to, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_nodes(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_parent(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorotree_roots(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_lorounknown(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_lorounknown(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_lorounknown_id(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_lorovaluelike(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_lorovaluelike(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_lorovaluelike(UniffiVTableCallbackInterfaceLoroValueLike vtable);
    RustBuffer.ByValue uniffi_loro_fn_method_lorovaluelike_as_loro_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_onpop(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_onpop(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_onpop(UniffiVTableCallbackInterfaceOnPop vtable);
    void uniffi_loro_fn_method_onpop_on_pop(Pointer ptr, RustBuffer.ByValue undoOrRedo, RustBuffer.ByValue span, RustBuffer.ByValue undoMeta, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_onpush(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_onpush(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_onpush(UniffiVTableCallbackInterfaceOnPush vtable);
    RustBuffer.ByValue uniffi_loro_fn_method_onpush_on_push(Pointer ptr, RustBuffer.ByValue undoOrRedo, RustBuffer.ByValue span, RustBuffer.ByValue diffEvent, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_styleconfigmap(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_styleconfigmap(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_styleconfigmap_default_rich_text_config(UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_styleconfigmap_new(UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_styleconfigmap_get(Pointer ptr, RustBuffer.ByValue key, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_styleconfigmap_insert(Pointer ptr, RustBuffer.ByValue key, RustBuffer.ByValue value, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_subscriber(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_subscriber(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_subscriber(UniffiVTableCallbackInterfaceSubscriber vtable);
    void uniffi_loro_fn_method_subscriber_on_diff(Pointer ptr, RustBuffer.ByValue diff, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_subscription(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_subscription(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_subscription_detach(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_subscription_unsubscribe(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_undomanager(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_undomanager(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_undomanager_new(Pointer doc, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_undomanager_add_exclude_origin_prefix(Pointer ptr, RustBuffer.ByValue prefix, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_undomanager_can_redo(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_undomanager_can_undo(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_undomanager_record_new_checkpoint(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_undomanager_redo(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_undomanager_set_max_undo_steps(Pointer ptr, Integer size, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_undomanager_set_merge_interval(Pointer ptr, Long interval, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_undomanager_set_on_pop(Pointer ptr, RustBuffer.ByValue onPop, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_undomanager_set_on_push(Pointer ptr, RustBuffer.ByValue onPush, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_undomanager_undo(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_unsubscriber(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_unsubscriber(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_init_callback_vtable_unsubscriber(UniffiVTableCallbackInterfaceUnsubscriber vtable);
    void uniffi_loro_fn_method_unsubscriber_on_unsubscribe(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_valueorcontainer(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_valueorcontainer(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_container(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_loro_counter(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_loro_list(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_loro_map(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_loro_movable_list(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_loro_text(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_loro_tree(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_loro_unknown(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_as_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_valueorcontainer_container_type(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_valueorcontainer_is_container(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_valueorcontainer_is_value(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_clone_versionvector(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_free_versionvector(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_versionvector_decode(RustBuffer.ByValue bytes, UniffiRustCallStatus uniffi_out_errmk);
    Pointer uniffi_loro_fn_constructor_versionvector_new(UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_versionvector_diff(Pointer ptr, Pointer rhs, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_versionvector_encode(Pointer ptr, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_versionvector_eq(Pointer ptr, Pointer other, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_versionvector_extend_to_include_vv(Pointer ptr, Pointer other, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_versionvector_get_last(Pointer ptr, Long peer, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_versionvector_get_missing_span(Pointer ptr, Pointer target, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_versionvector_includes_id(Pointer ptr, RustBuffer.ByValue id, UniffiRustCallStatus uniffi_out_errmk);
    Byte uniffi_loro_fn_method_versionvector_includes_vv(Pointer ptr, Pointer other, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_versionvector_intersect_span(Pointer ptr, RustBuffer.ByValue target, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_versionvector_merge(Pointer ptr, Pointer other, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_method_versionvector_partial_cmp(Pointer ptr, Pointer other, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_versionvector_set_end(Pointer ptr, RustBuffer.ByValue id, UniffiRustCallStatus uniffi_out_errmk);
    void uniffi_loro_fn_method_versionvector_set_last(Pointer ptr, RustBuffer.ByValue id, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_func_decode_import_blob_meta(RustBuffer.ByValue bytes, Byte checkChecksum, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue uniffi_loro_fn_func_get_version(UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue ffi_loro_rustbuffer_alloc(Long size, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue ffi_loro_rustbuffer_from_bytes(ForeignBytes.ByValue bytes, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rustbuffer_free(RustBuffer.ByValue buf, UniffiRustCallStatus uniffi_out_errmk);
    RustBuffer.ByValue ffi_loro_rustbuffer_reserve(RustBuffer.ByValue buf, Long additional, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_u8(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_u8(Long handle);
    void ffi_loro_rust_future_free_u8(Long handle);
    Byte ffi_loro_rust_future_complete_u8(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_i8(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_i8(Long handle);
    void ffi_loro_rust_future_free_i8(Long handle);
    Byte ffi_loro_rust_future_complete_i8(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_u16(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_u16(Long handle);
    void ffi_loro_rust_future_free_u16(Long handle);
    Short ffi_loro_rust_future_complete_u16(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_i16(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_i16(Long handle);
    void ffi_loro_rust_future_free_i16(Long handle);
    Short ffi_loro_rust_future_complete_i16(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_u32(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_u32(Long handle);
    void ffi_loro_rust_future_free_u32(Long handle);
    Integer ffi_loro_rust_future_complete_u32(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_i32(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_i32(Long handle);
    void ffi_loro_rust_future_free_i32(Long handle);
    Integer ffi_loro_rust_future_complete_i32(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_u64(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_u64(Long handle);
    void ffi_loro_rust_future_free_u64(Long handle);
    Long ffi_loro_rust_future_complete_u64(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_i64(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_i64(Long handle);
    void ffi_loro_rust_future_free_i64(Long handle);
    Long ffi_loro_rust_future_complete_i64(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_f32(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_f32(Long handle);
    void ffi_loro_rust_future_free_f32(Long handle);
    Float ffi_loro_rust_future_complete_f32(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_f64(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_f64(Long handle);
    void ffi_loro_rust_future_free_f64(Long handle);
    Double ffi_loro_rust_future_complete_f64(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_pointer(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_pointer(Long handle);
    void ffi_loro_rust_future_free_pointer(Long handle);
    Pointer ffi_loro_rust_future_complete_pointer(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_rust_buffer(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_rust_buffer(Long handle);
    void ffi_loro_rust_future_free_rust_buffer(Long handle);
    RustBuffer.ByValue ffi_loro_rust_future_complete_rust_buffer(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    void ffi_loro_rust_future_poll_void(Long handle, UniffiRustFutureContinuationCallback callback, Long callbackData);
    void ffi_loro_rust_future_cancel_void(Long handle);
    void ffi_loro_rust_future_free_void(Long handle);
    void ffi_loro_rust_future_complete_void(Long handle, UniffiRustCallStatus uniffi_out_errmk);
    Short uniffi_loro_checksum_func_decode_import_blob_meta();
    Short uniffi_loro_checksum_func_get_version();
    Short uniffi_loro_checksum_method_awareness_apply();
    Short uniffi_loro_checksum_method_awareness_encode();
    Short uniffi_loro_checksum_method_awareness_encode_all();
    Short uniffi_loro_checksum_method_awareness_get_all_states();
    Short uniffi_loro_checksum_method_awareness_get_local_state();
    Short uniffi_loro_checksum_method_awareness_peer();
    Short uniffi_loro_checksum_method_awareness_remove_outdated();
    Short uniffi_loro_checksum_method_awareness_set_local_state();
    Short uniffi_loro_checksum_method_changeancestorstraveler_travel();
    Short uniffi_loro_checksum_method_configure_fork();
    Short uniffi_loro_checksum_method_configure_merge_interval();
    Short uniffi_loro_checksum_method_configure_record_timestamp();
    Short uniffi_loro_checksum_method_configure_set_merge_interval();
    Short uniffi_loro_checksum_method_configure_set_record_timestamp();
    Short uniffi_loro_checksum_method_configure_text_style_config();
    Short uniffi_loro_checksum_method_containeridlike_as_container_id();
    Short uniffi_loro_checksum_method_diffbatch_get_diff();
    Short uniffi_loro_checksum_method_diffbatch_push();
    Short uniffi_loro_checksum_method_fractionalindex_to_string();
    Short uniffi_loro_checksum_method_frontiers_encode();
    Short uniffi_loro_checksum_method_frontiers_eq();
    Short uniffi_loro_checksum_method_localupdatecallback_on_local_update();
    Short uniffi_loro_checksum_method_lorocounter_decrement();
    Short uniffi_loro_checksum_method_lorocounter_doc();
    Short uniffi_loro_checksum_method_lorocounter_get_attached();
    Short uniffi_loro_checksum_method_lorocounter_get_value();
    Short uniffi_loro_checksum_method_lorocounter_id();
    Short uniffi_loro_checksum_method_lorocounter_increment();
    Short uniffi_loro_checksum_method_lorocounter_is_attached();
    Short uniffi_loro_checksum_method_lorocounter_is_deleted();
    Short uniffi_loro_checksum_method_lorodoc_apply_diff();
    Short uniffi_loro_checksum_method_lorodoc_attach();
    Short uniffi_loro_checksum_method_lorodoc_check_state_correctness_slow();
    Short uniffi_loro_checksum_method_lorodoc_checkout();
    Short uniffi_loro_checksum_method_lorodoc_checkout_to_latest();
    Short uniffi_loro_checksum_method_lorodoc_clear_next_commit_options();
    Short uniffi_loro_checksum_method_lorodoc_cmp_with_frontiers();
    Short uniffi_loro_checksum_method_lorodoc_commit();
    Short uniffi_loro_checksum_method_lorodoc_commit_with();
    Short uniffi_loro_checksum_method_lorodoc_compact_change_store();
    Short uniffi_loro_checksum_method_lorodoc_config();
    Short uniffi_loro_checksum_method_lorodoc_config_default_text_style();
    Short uniffi_loro_checksum_method_lorodoc_config_text_style();
    Short uniffi_loro_checksum_method_lorodoc_detach();
    Short uniffi_loro_checksum_method_lorodoc_diff();
    Short uniffi_loro_checksum_method_lorodoc_export_json_in_id_span();
    Short uniffi_loro_checksum_method_lorodoc_export_json_updates();
    Short uniffi_loro_checksum_method_lorodoc_export_json_updates_without_peer_compression();
    Short uniffi_loro_checksum_method_lorodoc_export_shallow_snapshot();
    Short uniffi_loro_checksum_method_lorodoc_export_snapshot();
    Short uniffi_loro_checksum_method_lorodoc_export_snapshot_at();
    Short uniffi_loro_checksum_method_lorodoc_export_state_only();
    Short uniffi_loro_checksum_method_lorodoc_export_updates();
    Short uniffi_loro_checksum_method_lorodoc_export_updates_in_range();
    Short uniffi_loro_checksum_method_lorodoc_find_id_spans_between();
    Short uniffi_loro_checksum_method_lorodoc_fork();
    Short uniffi_loro_checksum_method_lorodoc_fork_at();
    Short uniffi_loro_checksum_method_lorodoc_free_diff_calculator();
    Short uniffi_loro_checksum_method_lorodoc_free_history_cache();
    Short uniffi_loro_checksum_method_lorodoc_frontiers_to_vv();
    Short uniffi_loro_checksum_method_lorodoc_get_by_path();
    Short uniffi_loro_checksum_method_lorodoc_get_by_str_path();
    Short uniffi_loro_checksum_method_lorodoc_get_change();
    Short uniffi_loro_checksum_method_lorodoc_get_changed_containers_in();
    Short uniffi_loro_checksum_method_lorodoc_get_counter();
    Short uniffi_loro_checksum_method_lorodoc_get_cursor_pos();
    Short uniffi_loro_checksum_method_lorodoc_get_deep_value();
    Short uniffi_loro_checksum_method_lorodoc_get_deep_value_with_id();
    Short uniffi_loro_checksum_method_lorodoc_get_list();
    Short uniffi_loro_checksum_method_lorodoc_get_map();
    Short uniffi_loro_checksum_method_lorodoc_get_movable_list();
    Short uniffi_loro_checksum_method_lorodoc_get_path_to_container();
    Short uniffi_loro_checksum_method_lorodoc_get_pending_txn_len();
    Short uniffi_loro_checksum_method_lorodoc_get_text();
    Short uniffi_loro_checksum_method_lorodoc_get_tree();
    Short uniffi_loro_checksum_method_lorodoc_get_value();
    Short uniffi_loro_checksum_method_lorodoc_has_container();
    Short uniffi_loro_checksum_method_lorodoc_has_history_cache();
    Short uniffi_loro_checksum_method_lorodoc_import();
    Short uniffi_loro_checksum_method_lorodoc_import_batch();
    Short uniffi_loro_checksum_method_lorodoc_import_json_updates();
    Short uniffi_loro_checksum_method_lorodoc_import_with();
    Short uniffi_loro_checksum_method_lorodoc_is_detached();
    Short uniffi_loro_checksum_method_lorodoc_is_shallow();
    Short uniffi_loro_checksum_method_lorodoc_jsonpath();
    Short uniffi_loro_checksum_method_lorodoc_len_changes();
    Short uniffi_loro_checksum_method_lorodoc_len_ops();
    Short uniffi_loro_checksum_method_lorodoc_log_estimate_size();
    Short uniffi_loro_checksum_method_lorodoc_minimize_frontiers();
    Short uniffi_loro_checksum_method_lorodoc_oplog_frontiers();
    Short uniffi_loro_checksum_method_lorodoc_oplog_vv();
    Short uniffi_loro_checksum_method_lorodoc_peer_id();
    Short uniffi_loro_checksum_method_lorodoc_revert_to();
    Short uniffi_loro_checksum_method_lorodoc_set_change_merge_interval();
    Short uniffi_loro_checksum_method_lorodoc_set_next_commit_message();
    Short uniffi_loro_checksum_method_lorodoc_set_next_commit_options();
    Short uniffi_loro_checksum_method_lorodoc_set_next_commit_origin();
    Short uniffi_loro_checksum_method_lorodoc_set_next_commit_timestamp();
    Short uniffi_loro_checksum_method_lorodoc_set_peer_id();
    Short uniffi_loro_checksum_method_lorodoc_set_record_timestamp();
    Short uniffi_loro_checksum_method_lorodoc_shallow_since_vv();
    Short uniffi_loro_checksum_method_lorodoc_state_frontiers();
    Short uniffi_loro_checksum_method_lorodoc_state_vv();
    Short uniffi_loro_checksum_method_lorodoc_subscribe();
    Short uniffi_loro_checksum_method_lorodoc_subscribe_local_update();
    Short uniffi_loro_checksum_method_lorodoc_subscribe_root();
    Short uniffi_loro_checksum_method_lorodoc_travel_change_ancestors();
    Short uniffi_loro_checksum_method_lorodoc_vv_to_frontiers();
    Short uniffi_loro_checksum_method_lorolist_clear();
    Short uniffi_loro_checksum_method_lorolist_delete();
    Short uniffi_loro_checksum_method_lorolist_doc();
    Short uniffi_loro_checksum_method_lorolist_get();
    Short uniffi_loro_checksum_method_lorolist_get_attached();
    Short uniffi_loro_checksum_method_lorolist_get_cursor();
    Short uniffi_loro_checksum_method_lorolist_get_deep_value();
    Short uniffi_loro_checksum_method_lorolist_get_id_at();
    Short uniffi_loro_checksum_method_lorolist_get_value();
    Short uniffi_loro_checksum_method_lorolist_id();
    Short uniffi_loro_checksum_method_lorolist_insert();
    Short uniffi_loro_checksum_method_lorolist_insert_counter_container();
    Short uniffi_loro_checksum_method_lorolist_insert_list_container();
    Short uniffi_loro_checksum_method_lorolist_insert_map_container();
    Short uniffi_loro_checksum_method_lorolist_insert_movable_list_container();
    Short uniffi_loro_checksum_method_lorolist_insert_text_container();
    Short uniffi_loro_checksum_method_lorolist_insert_tree_container();
    Short uniffi_loro_checksum_method_lorolist_is_attached();
    Short uniffi_loro_checksum_method_lorolist_is_deleted();
    Short uniffi_loro_checksum_method_lorolist_is_empty();
    Short uniffi_loro_checksum_method_lorolist_len();
    Short uniffi_loro_checksum_method_lorolist_pop();
    Short uniffi_loro_checksum_method_lorolist_push();
    Short uniffi_loro_checksum_method_lorolist_to_vec();
    Short uniffi_loro_checksum_method_loromap_clear();
    Short uniffi_loro_checksum_method_loromap_delete();
    Short uniffi_loro_checksum_method_loromap_doc();
    Short uniffi_loro_checksum_method_loromap_get();
    Short uniffi_loro_checksum_method_loromap_get_attached();
    Short uniffi_loro_checksum_method_loromap_get_deep_value();
    Short uniffi_loro_checksum_method_loromap_get_last_editor();
    Short uniffi_loro_checksum_method_loromap_get_or_create_counter_container();
    Short uniffi_loro_checksum_method_loromap_get_or_create_list_container();
    Short uniffi_loro_checksum_method_loromap_get_or_create_map_container();
    Short uniffi_loro_checksum_method_loromap_get_or_create_movable_list_container();
    Short uniffi_loro_checksum_method_loromap_get_or_create_text_container();
    Short uniffi_loro_checksum_method_loromap_get_or_create_tree_container();
    Short uniffi_loro_checksum_method_loromap_get_value();
    Short uniffi_loro_checksum_method_loromap_id();
    Short uniffi_loro_checksum_method_loromap_insert();
    Short uniffi_loro_checksum_method_loromap_insert_counter_container();
    Short uniffi_loro_checksum_method_loromap_insert_list_container();
    Short uniffi_loro_checksum_method_loromap_insert_map_container();
    Short uniffi_loro_checksum_method_loromap_insert_movable_list_container();
    Short uniffi_loro_checksum_method_loromap_insert_text_container();
    Short uniffi_loro_checksum_method_loromap_insert_tree_container();
    Short uniffi_loro_checksum_method_loromap_is_attached();
    Short uniffi_loro_checksum_method_loromap_is_deleted();
    Short uniffi_loro_checksum_method_loromap_is_empty();
    Short uniffi_loro_checksum_method_loromap_keys();
    Short uniffi_loro_checksum_method_loromap_len();
    Short uniffi_loro_checksum_method_loromap_values();
    Short uniffi_loro_checksum_method_loromovablelist_clear();
    Short uniffi_loro_checksum_method_loromovablelist_delete();
    Short uniffi_loro_checksum_method_loromovablelist_doc();
    Short uniffi_loro_checksum_method_loromovablelist_get();
    Short uniffi_loro_checksum_method_loromovablelist_get_attached();
    Short uniffi_loro_checksum_method_loromovablelist_get_creator_at();
    Short uniffi_loro_checksum_method_loromovablelist_get_cursor();
    Short uniffi_loro_checksum_method_loromovablelist_get_deep_value();
    Short uniffi_loro_checksum_method_loromovablelist_get_last_editor_at();
    Short uniffi_loro_checksum_method_loromovablelist_get_last_mover_at();
    Short uniffi_loro_checksum_method_loromovablelist_get_value();
    Short uniffi_loro_checksum_method_loromovablelist_id();
    Short uniffi_loro_checksum_method_loromovablelist_insert();
    Short uniffi_loro_checksum_method_loromovablelist_insert_counter_container();
    Short uniffi_loro_checksum_method_loromovablelist_insert_list_container();
    Short uniffi_loro_checksum_method_loromovablelist_insert_map_container();
    Short uniffi_loro_checksum_method_loromovablelist_insert_movable_list_container();
    Short uniffi_loro_checksum_method_loromovablelist_insert_text_container();
    Short uniffi_loro_checksum_method_loromovablelist_insert_tree_container();
    Short uniffi_loro_checksum_method_loromovablelist_is_attached();
    Short uniffi_loro_checksum_method_loromovablelist_is_deleted();
    Short uniffi_loro_checksum_method_loromovablelist_is_empty();
    Short uniffi_loro_checksum_method_loromovablelist_len();
    Short uniffi_loro_checksum_method_loromovablelist_mov();
    Short uniffi_loro_checksum_method_loromovablelist_pop();
    Short uniffi_loro_checksum_method_loromovablelist_push();
    Short uniffi_loro_checksum_method_loromovablelist_set();
    Short uniffi_loro_checksum_method_loromovablelist_set_counter_container();
    Short uniffi_loro_checksum_method_loromovablelist_set_list_container();
    Short uniffi_loro_checksum_method_loromovablelist_set_map_container();
    Short uniffi_loro_checksum_method_loromovablelist_set_movable_list_container();
    Short uniffi_loro_checksum_method_loromovablelist_set_text_container();
    Short uniffi_loro_checksum_method_loromovablelist_set_tree_container();
    Short uniffi_loro_checksum_method_loromovablelist_to_vec();
    Short uniffi_loro_checksum_method_lorotext_apply_delta();
    Short uniffi_loro_checksum_method_lorotext_delete();
    Short uniffi_loro_checksum_method_lorotext_delete_utf8();
    Short uniffi_loro_checksum_method_lorotext_doc();
    Short uniffi_loro_checksum_method_lorotext_get_attached();
    Short uniffi_loro_checksum_method_lorotext_get_cursor();
    Short uniffi_loro_checksum_method_lorotext_get_editor_at_unicode_pos();
    Short uniffi_loro_checksum_method_lorotext_get_richtext_value();
    Short uniffi_loro_checksum_method_lorotext_id();
    Short uniffi_loro_checksum_method_lorotext_insert();
    Short uniffi_loro_checksum_method_lorotext_insert_utf8();
    Short uniffi_loro_checksum_method_lorotext_is_attached();
    Short uniffi_loro_checksum_method_lorotext_is_deleted();
    Short uniffi_loro_checksum_method_lorotext_is_empty();
    Short uniffi_loro_checksum_method_lorotext_len_unicode();
    Short uniffi_loro_checksum_method_lorotext_len_utf16();
    Short uniffi_loro_checksum_method_lorotext_len_utf8();
    Short uniffi_loro_checksum_method_lorotext_mark();
    Short uniffi_loro_checksum_method_lorotext_push_str();
    Short uniffi_loro_checksum_method_lorotext_slice();
    Short uniffi_loro_checksum_method_lorotext_splice();
    Short uniffi_loro_checksum_method_lorotext_to_delta();
    Short uniffi_loro_checksum_method_lorotext_to_string();
    Short uniffi_loro_checksum_method_lorotext_unmark();
    Short uniffi_loro_checksum_method_lorotext_update();
    Short uniffi_loro_checksum_method_lorotext_update_by_line();
    Short uniffi_loro_checksum_method_lorotree_children();
    Short uniffi_loro_checksum_method_lorotree_children_num();
    Short uniffi_loro_checksum_method_lorotree_contains();
    Short uniffi_loro_checksum_method_lorotree_create();
    Short uniffi_loro_checksum_method_lorotree_create_at();
    Short uniffi_loro_checksum_method_lorotree_delete();
    Short uniffi_loro_checksum_method_lorotree_disable_fractional_index();
    Short uniffi_loro_checksum_method_lorotree_doc();
    Short uniffi_loro_checksum_method_lorotree_enable_fractional_index();
    Short uniffi_loro_checksum_method_lorotree_fractional_index();
    Short uniffi_loro_checksum_method_lorotree_get_attached();
    Short uniffi_loro_checksum_method_lorotree_get_last_move_id();
    Short uniffi_loro_checksum_method_lorotree_get_meta();
    Short uniffi_loro_checksum_method_lorotree_get_value();
    Short uniffi_loro_checksum_method_lorotree_get_value_with_meta();
    Short uniffi_loro_checksum_method_lorotree_id();
    Short uniffi_loro_checksum_method_lorotree_is_attached();
    Short uniffi_loro_checksum_method_lorotree_is_deleted();
    Short uniffi_loro_checksum_method_lorotree_is_fractional_index_enabled();
    Short uniffi_loro_checksum_method_lorotree_is_node_deleted();
    Short uniffi_loro_checksum_method_lorotree_mov();
    Short uniffi_loro_checksum_method_lorotree_mov_after();
    Short uniffi_loro_checksum_method_lorotree_mov_before();
    Short uniffi_loro_checksum_method_lorotree_mov_to();
    Short uniffi_loro_checksum_method_lorotree_nodes();
    Short uniffi_loro_checksum_method_lorotree_parent();
    Short uniffi_loro_checksum_method_lorotree_roots();
    Short uniffi_loro_checksum_method_lorounknown_id();
    Short uniffi_loro_checksum_method_lorovaluelike_as_loro_value();
    Short uniffi_loro_checksum_method_onpop_on_pop();
    Short uniffi_loro_checksum_method_onpush_on_push();
    Short uniffi_loro_checksum_method_styleconfigmap_get();
    Short uniffi_loro_checksum_method_styleconfigmap_insert();
    Short uniffi_loro_checksum_method_subscriber_on_diff();
    Short uniffi_loro_checksum_method_subscription_detach();
    Short uniffi_loro_checksum_method_subscription_unsubscribe();
    Short uniffi_loro_checksum_method_undomanager_add_exclude_origin_prefix();
    Short uniffi_loro_checksum_method_undomanager_can_redo();
    Short uniffi_loro_checksum_method_undomanager_can_undo();
    Short uniffi_loro_checksum_method_undomanager_record_new_checkpoint();
    Short uniffi_loro_checksum_method_undomanager_redo();
    Short uniffi_loro_checksum_method_undomanager_set_max_undo_steps();
    Short uniffi_loro_checksum_method_undomanager_set_merge_interval();
    Short uniffi_loro_checksum_method_undomanager_set_on_pop();
    Short uniffi_loro_checksum_method_undomanager_set_on_push();
    Short uniffi_loro_checksum_method_undomanager_undo();
    Short uniffi_loro_checksum_method_unsubscriber_on_unsubscribe();
    Short uniffi_loro_checksum_method_valueorcontainer_as_container();
    Short uniffi_loro_checksum_method_valueorcontainer_as_loro_counter();
    Short uniffi_loro_checksum_method_valueorcontainer_as_loro_list();
    Short uniffi_loro_checksum_method_valueorcontainer_as_loro_map();
    Short uniffi_loro_checksum_method_valueorcontainer_as_loro_movable_list();
    Short uniffi_loro_checksum_method_valueorcontainer_as_loro_text();
    Short uniffi_loro_checksum_method_valueorcontainer_as_loro_tree();
    Short uniffi_loro_checksum_method_valueorcontainer_as_loro_unknown();
    Short uniffi_loro_checksum_method_valueorcontainer_as_value();
    Short uniffi_loro_checksum_method_valueorcontainer_container_type();
    Short uniffi_loro_checksum_method_valueorcontainer_is_container();
    Short uniffi_loro_checksum_method_valueorcontainer_is_value();
    Short uniffi_loro_checksum_method_versionvector_diff();
    Short uniffi_loro_checksum_method_versionvector_encode();
    Short uniffi_loro_checksum_method_versionvector_eq();
    Short uniffi_loro_checksum_method_versionvector_extend_to_include_vv();
    Short uniffi_loro_checksum_method_versionvector_get_last();
    Short uniffi_loro_checksum_method_versionvector_get_missing_span();
    Short uniffi_loro_checksum_method_versionvector_includes_id();
    Short uniffi_loro_checksum_method_versionvector_includes_vv();
    Short uniffi_loro_checksum_method_versionvector_intersect_span();
    Short uniffi_loro_checksum_method_versionvector_merge();
    Short uniffi_loro_checksum_method_versionvector_partial_cmp();
    Short uniffi_loro_checksum_method_versionvector_set_end();
    Short uniffi_loro_checksum_method_versionvector_set_last();
    Short uniffi_loro_checksum_constructor_awareness_new();
    Short uniffi_loro_checksum_constructor_cursor_new();
    Short uniffi_loro_checksum_constructor_diffbatch_new();
    Short uniffi_loro_checksum_constructor_fractionalindex_from_bytes();
    Short uniffi_loro_checksum_constructor_fractionalindex_from_hex_string();
    Short uniffi_loro_checksum_constructor_frontiers_decode();
    Short uniffi_loro_checksum_constructor_frontiers_from_id();
    Short uniffi_loro_checksum_constructor_frontiers_from_ids();
    Short uniffi_loro_checksum_constructor_frontiers_new();
    Short uniffi_loro_checksum_constructor_lorocounter_new();
    Short uniffi_loro_checksum_constructor_lorodoc_new();
    Short uniffi_loro_checksum_constructor_lorolist_new();
    Short uniffi_loro_checksum_constructor_loromap_new();
    Short uniffi_loro_checksum_constructor_loromovablelist_new();
    Short uniffi_loro_checksum_constructor_lorotext_new();
    Short uniffi_loro_checksum_constructor_lorotree_new();
    Short uniffi_loro_checksum_constructor_styleconfigmap_default_rich_text_config();
    Short uniffi_loro_checksum_constructor_styleconfigmap_new();
    Short uniffi_loro_checksum_constructor_undomanager_new();
    Short uniffi_loro_checksum_constructor_versionvector_decode();
    Short uniffi_loro_checksum_constructor_versionvector_new();
    Integer ffi_loro_uniffi_contract_version();
    
}

