[package]
name = "loro-swift"
version = "0.16.2"
edition = "2021"

[lib]
name = "loro"
crate-type = ["cdylib", "staticlib"]

[[bin]]
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"


[dependencies]
# loro-ffi = { path = "../../loro/crates/loro-ffi" }
loro-ffi = { git = "https://github.com/loro-dev/loro.git", rev = "832bc6581b21efc2e6c7b46d2e3c78f85a128257" }
uniffi = { version = "0.28" }

[build-dependencies]
uniffi = { version = "0.28", features = ["build"] }

[features]
cli = ["uniffi/cli"]
