name: build-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: macos-14
    env:
      LOCAL_BUILD: true
      DEVELOPER_DIR: /Applications/Xcode_15.4.app
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.78.0
          default: true
      - name: get xcode information
        run: |
          xcodebuild -version
          swift --version
      - name: build xcframework
        run: ./scripts/build_swift_ffi.sh
      - name: Swift tests
        run: swift test
